### ISSUE TITLE
[Feature Request] Provide a way to augment SDK workflow and activity resolution

### ISSUE THREAD

**Issue by bergundy** [temporalio/features#125]
Java has DynamicWorkflow and DynamicActivity that serve as fallback for when the SDK does not find a matching workflow or activity implementation to execute.

Other SDKs should surface this functionality as well.

Some alternative APIs discussed in slack were:
1. providing additional inbound interceptor methods (e.g `resolve` | `prepare` | `preExecute`)
2. a worker option callback

**Comment by josh-berry** [comment]
This feels like it might be old—do we have tickets already for the various SDKs that don't already have dynamic workflow/activity support? Which SDKs are still missing this?

**Comment by Quinn-With-Two-Ns** [comment]
I believe it is only Go https://github.com/temporalio/sdk-go/issues/543

**Comment by cretz** [comment]
> do we have tickets already for the various SDKs that don't already have dynamic workflow/activity support? Which SDKs are still missing this?

Yes, #201. Go and TypeScript. This issue can probably be closed.
