### ISSUE TITLE
[Feature Request] Add gRPC error status code tag to request metrics

### ISSUE THREAD

**Issue by bergundy** [temporalio/features#144]
This should be available server-side so there might be duplication.
Need to investigate whether it's worth adding this.

**Comment by yiminc** [comment]
It is useful to expose resource exhausted error and their cause as tag to metrics.

Not all user has access to all server side metrics. So this is critical.

**Comment by cretz** [comment]
While gRPC code makes sense, I question "cause" though assuming it's just the message. Resource exhausted is also commonly returned by proxies. Also even if an error message is a fixed set now, most developers don't assume it is used that way and may append something in the future blowing up cardinality. If a specific "cause" is needed, server should add it to a known proto in the status/error details.

**Comment by cretz** [comment]
We are making a `temporal_request_resource_exhausted` and `temporal_long_request_resource_exhausted` that have the same tags as `X_request_failure` but also have a `cause` which is the "string" of https://github.com/temporalio/api/blob/e381e51864ec8f43a90750ef936705258b8f64b2/temporal/api/enums/v1/failed_cause.proto#L90.

For SDK implementers, to match server this is not a normal enum string. Rather, this is auto-generated from our gogo proto hack. Use one of the strings at https://github.com/temporalio/api-go/blob/3622cc780d3eee12a6f29788460fdf7d3c94f048/enums/v1/failed_cause.pb.go#L235-L241.

**Comment by cretz** [comment]
To clarify for issue readers, the resource exhausted tangent is unrelated to the general request for error codes on request metrics.

**Comment by Sushisource** [comment]
Used label `status_code` and the SCREAMING_SNAKE names from the gRPC spec as the values for codes.
