### ISSUE TITLE
[Bug] Flaky tests

### ISSUE THREAD

**Issue by bergundy** [temporalio/features#172]
TypeScript docker: https://github.com/temporalio/sdk-features/actions/runs/3528486923/jobs/5918644287
Java docker: https://github.com/temporalio/sdk-features/actions/runs/3528486923/jobs/5918643970

**Comment by cretz** [comment]
Specifically for those searching issues:

> Feature query/unexpected_query_type_name failed with AssertionError [ERR_ASSERTION]: The error is expected to be an instance of "QueryNotRegisteredError". Received "ServiceError"

**Comment by bergundy** [comment]
Should be fixed once the SDK is upgraded

**Comment by Sushisource** [comment]
Closing old bug
