### ISSUE TITLE
[Feature Request] Support a "version marker" like approach for internal SDK use for every workflow

### ISSUE THREAD

**Issue by cretz** [temporalio/features#200]
### Is your feature request related to a problem? Please describe.

SDKs need to fix things that don't affect older workflows sometimes. 

### Describe the solution you'd like

We should get to leverage the same type of versioning/patching our users do. However, it may be a bit unreasonable to add a new marker event for every single workflow henceforth (we charge for these). So we should consider maybe adding some kind of incremental integer to `temporal.api.workflowservice.v1.RespondWorkflowTaskCompletedRequest` that will appear on `temporal.api.history.v1.WorkflowTaskCompletedEventAttributes`.

Or maybe we add something inside `temporal.api.taskqueue.v1.VersionId`?

Either way, we also need to relay this capability in the capabilities response from server's get system info since we need to know whether we can add SDK versions on the _first_ task and therefore leverage it at all. E.g. if we need to fix the non-zero timer doesn't create task issue in Go, we need to know that the server supports this kind of versioning before applying fix (if it doesn't we won't have this value on replay).

**Comment by Sushisource** [comment]
This should've been closed way back.
