### ISSUE TITLE
[Bug] '/home/runner/work/temporal/temporal/./features'. No such file or directory

### ISSUE THREAD

**Issue by bergundy** [temporalio/features#216]
Test failing with:

```
Error: An error occurred trying to start process '/usr/bin/bash' with working directory '/home/runner/work/temporal/temporal/./features'. No such file or directory
```

https://github.com/temporalio/temporal/actions/runs/3961521809/jobs/6787213991

**Comment by bergundy** [comment]
More context: This is happening on docker-compose shutdown, it seems like a flake and I'm not sure when it started.

**Comment by josh-berry** [comment]
I looked at runs against `main` in the last month, and all of them seem to be passing, or failing for unrelated reasons. @bergundy Can this be closed?
