### ISSUE TITLE
[Feature Request] Send SDK name and version on workflow task completion

### ISSUE THREAD

**Issue by bergundy** [temporalio/features#232]
The information should be persisted in the `WorkflowTaskCompleted` event for debugging purposes.

Possibly, we'd use the [sdk_metadata](https://github.com/temporalio/api/blob/44e4397262d480b9e6f17771be9ae1812d97384e/temporal/api/history/v1/message.proto#L201) field to store this.

**Comment by cretz** [comment]
Can you clarify the debugging purpose for adding this information to every task complete? Specifically, what are people unable to do today that this would enable? Is there concern a user does not know the SDK and version they are running under and/or we would be unwilling to ask for that if we are debugging?

**Comment by mfateev** [comment]
For storage size reasons, we can send them only if they have changed since the previous workflow task. 

I believe knowing the exact SDK version might help in troubleshooting certain failure scenarios.

**Comment by Quinn-With-Two-Ns** [comment]
Duplicate of  https://github.com/temporalio/features/issues/321
