### ISSUE TITLE
Swift SDK

### ISSUE THREAD

**Issue by mgesmundo** [temporalio/features#245]
Hello,
there is a plan to add a Swift SDK? Do you have some guidelines to develop it myself and share here if there is some interest?
Thank you.
All the best

**Comment by bergundy** [comment]
Hi,

There currently is no plan to officially support a Swift SDK.
If you were to take this on, I would go over some of these proposals for reference:

https://github.com/temporalio/proposals/tree/master/dotnet
https://github.com/temporalio/proposals/tree/master/python

And base your SDK on our Rust Core SDK as we have done for the recent SDKs we've developed.

https://github.com/temporalio/sdk-core

**Comment by mgesmundo** [comment]
Thank you @bergundy 
All the best.
