### ISSUE TITLE
[Feature Request] Expose build ID via WorkflowInfo.

### ISSUE THREAD

**Issue by bergundy** [temporalio/features#253]
### Is your feature request related to a problem? Please describe.

Workers are identified by a build ID (a.k.a binary checksum), which is stored on workflow task completions for debugging and resetting purposes.

When a user makes a bad deployment that breaks determinism - e.g. adding an activity - without using workflow versioning, there may be histories generated by both old and new versions of workflow code.
When the system reaches this state, versioning APIs may not be used since they will cause further non determinism.
At this point, users will either terminate, reset, or try to deploy new workflow code that uses start time or other heuristics for switching the old/new logic.

### Describe the solution you'd like

Expose build ID via WorkflowInfo so that users can switch based on it and unblock both new and old workflows.

**Comment by bergundy** [comment]
I just reopened this, we need it in Java and Go too and to be exposed in lang SDKs on top of Core.

**Comment by cretz** [comment]
Can you clarify whether we should consider this "unsafe" information? Also, can you come up with a good name for "most recent build ID" that we can share across SDKs?

**Comment by bergundy** [comment]
It safe to use since the build ID is taken from workflow task completion.

I think `latest build ID` or `most recent build ID` both work.

**Comment by Sushisource** [comment]
Done everywhere
