### ISSUE TITLE
[Feature Request] Expose TemporalScheduledStartTime search attribute as typed datetime from workflow info

### ISSUE THREAD

**Issue by cretz** [temporalio/features#258]
### Describe the solution you'd like

This info is already available as a search attribute, need language-friendly exposure of it instead of requiring they use string names.

**Comment by Quinn-With-Two-Ns** [comment]
duplicate of https://github.com/temporalio/features/issues/243?

**Comment by cretz** [comment]
Yes! Closing in favor of that one.
