### ISSUE TITLE
[Feature Request]  Update feature tests

### ISSUE THREAD

**Issue by Quinn-With-Two-Ns** [temporalio/features#266]
### Is your feature request related to a problem? Please describe.
Add feature tests for update workflow.

- [x] Go
- [x] Java
- [x] Typescript
- [x] Python
- [ ] Dotnet

https://github.com/temporalio/features/tree/main/features/update

**Comment by josh-berry** [comment]
Do we need #150 for this? I noticed that the update tests are failing in CI because the server version is too old.
