### ISSUE TITLE
[Feature Request] Unified client gRPC retry periods

### ISSUE THREAD

**Issue by lorensr** [temporalio/features#326]
### Is your feature request related to a problem? Please describe.

CGS believes all SDKs retry for longer than the longest namespace migration Unavailable period (10s), which is why they say that Cloud's expected downtime is not SDK calls failing—it's just higher latency. It's [possible](https://github.com/temporalio/sdk-typescript/pull/1012) for the TS Client to retry for less than that.

### Describe the solution you'd like

Figure out what default retry period we want Clients to have (& maybe ask Server & Cloud teams what they want Clients to do) and apply it across the board. IMO it should be at least 10s + some buffer.

I think all Workers indefinitely retry retryable error codes, but we could confirm that while we're at it.

### Current status

* TS: 
  * [Client](https://github.com/temporalio/sdk-typescript/blob/8112c9fcd666f093091fc5515b097a8179a59b50/packages/client/src/grpc-retry.ts#L69-L77): maxAttempts 10, factor 2, initial interval 20ms (see [spreadsheet](https://github.com/temporalio/sdk-typescript/pull/1012) with minimum cumulative)
  * Worker: indefinite
* Java:
  * [Client](https://github.com/temporalio/sdk-java/blob/efce2f17cc373cc717cf9152c0d5f59d9969c139/temporal-serviceclient/src/main/java/io/temporal/serviceclient/rpcretry/DefaultStubServiceOperationRpcRetryOptions.java#L34): 1m
  * Worker: indefinite

### Related
https://github.com/temporalio/features/issues/27

**Comment by lorensr** [comment]
Also make sure that Clients retry the initial connection, not just methods called after connection is set up. 

@rross reports that Java Client doesn't retry.

TypeScript does:

<img width="724" alt="image" src="https://github.com/temporalio/features/assets/251288/7dab083a-3405-447a-9e60-127906da60d5">

**Comment by chronos-tachyon** [comment]
NB: the Java retry issue has been filed as a separate ticket (SDK-1742 in internal Jira) that I hope to get to in the next two weeks.  There currently isn't a public GitHub ticket but I'd be happy to create one if it's needed.
