### ISSUE TITLE
[Feature Request] Allow Continue-as-New from update handlers

### ISSUE THREAD

**Issue by Quinn-With-Two-Ns** [temporalio/features#379]
### Is your feature request related to a problem? Please describe.

Users may want to continue as new from update handlers the same way they continue as new from signal handlers

Note: The Go SDK is intentionally left out of this due to how continue as new is exposed 

* [x] Java
* [ ] TypeScript
* [ ] Python - https://github.com/temporalio/sdk-python/issues/439
* [ ] .NET - https://github.com/temporalio/sdk-dotnet/issues/161

**Comment by Quinn-With-Two-Ns** [comment]
An option question is if the workflow method completes and the update method continues-as-new in the same WFT which takes precedent

**Comment by cretz** [comment]
We have since decided against doing this. I am opening an issue in Java to revert.
