### ISSUE TITLE
[Feature Request] Whitelist Retryable Error Types

### ISSUE THREAD

**Issue by sebl1ngt0n** [temporalio/features#387]
Add the ability to "whitelist" error types that you want your RetryPolicy to handle.

```
RetryPolicy = new Temporalio.Common.RetryPolicy
{
    RetryableErrorTypes = [ "RetryableError" ]
}
```

**Comment by cretz** [comment]
Closing issue for now, but @sebl1ngt0n - feel free to add more clarity as a comment (and reopen if desired) or join us on `#dotnet-sdk` on Slack to discuss options here.
