### ISSUE TITLE
[Feature Request] Do not require other Activity timeouts when Heartbeat timeout is specified

### ISSUE THREAD

**Issue by husam-e** [temporalio/features#397]
### Is your feature request related to a problem? Please describe.

Activities currently require setting either a `StartToClose` or `ScheduleToClose` timeout.

This does not lend itself well to indefinite or "infinite" activities, and requires users to set some large timeout value as a workaround.

### Describe the solution you'd like

Relax the requirement for other timeouts whenever a `Heartbeat` timeout is set, as that indicates that the activity is long running and ensures that there is a mechanism to kill it and reschedule if it's not making progress.

### Additional context

Discussed with Temporal support who requested that an issue be raised for this.

**Comment by Quinn-With-Two-Ns** [comment]
This is a duplicate of https://github.com/temporalio/features/issues/377, marking as closed to keep the discussion organized
