### ISSUE TITLE
Make start_update users aware that it's synchronous w/ worker.

### ISSUE THREAD

**Issue by drewhoskins-temporal** [temporalio/features#469]
### Is your feature request related to a problem? Please describe.

By default, `start_update` waits until the (often remote) worker accepts it.

It misleads customers into thinking it's fully async, as `start_activity` and `start_workflow` are.  Customers won’t be aware that the remote worker blocks this call and might inadvertently take a dependency on a worker, for example, that has a lower availability level than the service calling it.  Such a mistake would cause an outage to a critical service.

In the future, we want users to be able to choose durable-on-admitted.  Removing the default here would make space for that.

### Describe the solution you'd like
We decided to force customers to explicitly pass in a flag saying what’s being awaited. (e.g. start_update(wait_for_stage=ACCEPTED/COMPLETED)) and then if they don’t provide it.
We should also make sure the comments are clear that the remote worker must be present for the operation to work.

### Per-SDK Tickets

- [x] Go - https://github.com/temporalio/sdk-go/issues/1449
- [x] Java - https://github.com/temporalio/sdk-java/issues/2045
- [x] Core - 
- [x] TypeScript - https://github.com/temporalio/sdk-typescript/issues/1403
- [x] Python - https://github.com/temporalio/sdk-python/issues/514
- [x] .NET - https://github.com/temporalio/sdk-dotnet/issues/231
- [x] PHP - https://github.com/temporalio/sdk-php/issues/426
- [x] Temporal CLI - https://github.com/temporalio/cli/issues/597

**Comment by josh-berry** [comment]
Closing since afaik this is done. @drewhoskins-temporal please re-open if you disagree.
