### ISSUE TITLE
Workflow-friendly concurrency control

### ISSUE THREAD

**Issue by drewhoskins-temporal** [temporalio/features#500]
We need a mechanism for concurrency control (mutex/semaphore) that fits with the language but is reentrant and deterministic within workflow coroutines.  To be used within signal and update handlers and the main workflow coroutine.

- [x] PHP https://github.com/temporalio/sdk-php/issues/462
- [x] TypeScript https://github.com/temporalio/sdk-typescript/issues/1446
- [x] Go https://github.com/temporalio/sdk-go/issues/1521
- [x] Java https://github.com/temporalio/sdk-java/issues/2116
- [x] .NET https://github.com/temporalio/sdk-dotnet/issues/281
- [x] Python https://github.com/temporalio/sdk-python/issues/554

**Comment by josh-berry** [comment]
Closing because I think this is done. @drewhoskins-temporal please reopen if you disagree.
