### ISSUE TITLE
Create FIFO mutex mechanism for locking access to some part of a workflow

### ISSUE THREAD

**Issue by Noot-tooN** [temporalio/features#565]
### Is your feature request related to a problem? Please describe.

Imagine that you want to guarantee a chain of events for some user as they come in the workflow.
First created event (lets call it event `A`) inside the workflow will have no parent
Second created event (event `B`) inside the workflow should have event `A` as parent, etc...

You can imagine the following pseudo code:
1. Get latest from DB
2. Run a long lasting `if` branch if result from step 1 fulfills some constraints
3. Create row in DB with parent from step 1 if its not null

We would need to guarantee that for some user id `Get` from second workflow doesn't execute before the `Create` from first workflow is finished.

### Describe the solution you'd like

I would like to have some workflow function that i could simply call to Lock or Unlock critical sections of the code.
For example, taking in the previous example
1. `workflow.Lock(ctx, "someLockKey")`
2. Get latest from DB
3. Run a long lasting `if` branch if result from step 1 fulfills some constraints
4. Create row in DB with parent from step 1 if its not null
5. `workflow.Unlock(ctx, "someLockKey")`

The `Lock` and `Unlock` functionality should be able to lock based on some key. In my case that would be some `userId` for example, but i believe that should be general enough for any use case.
The mechanism would need to guarantee FIFO order.

### Per-SDK Tickets

- [ ] Go - 
- [ ] Java - 
- [ ] Core - 
- [ ] TypeScript - 
- [ ] Python - 
- [ ] .NET - 
- [ ] Ruby - 
- [ ] PHP - 
- [ ] Temporal CLI -

**Comment by cretz** [comment]
> I would like to have some workflow function that i could simply call to Lock or Unlock critical sections of the code.

Mutex support that mimics the language's standard library equivalent (or reuses it) should already exist now in all SDKs as part of #500. For example, `workflow.NewMutex` now exists to return a `workflow.Mutex` that can be used similarly to `sync.Mutex` in the standard library. If you need key-specific mutexes, you can do that the same way you would with `sync.Mutex`.

**Comment by Noot-tooN** [comment]
I am not sure if this can be achieved with a regular mutex.

If i were to just use a mutex it would lock a specific workflow type for all other workers, and that's not what i want to achieve.

In order to achieve the key-specific mutex i think that i would have to implement some kind of never ending for loop in a separate workflow (it would act as a centralised lock manager) that would have a `map[string]MutexQueue` and 2 channels 1 for locking and 1 for unlocking and perform async actions on the appropriate queues from the map.
But i think this is an anti-pattern in Temporal. Also that would probably get filled up quickly because there is a limit of 50k events per workflow. At that point in time i would probably have to perform continue-as-new but that would lose the potentially filled up queues in the map.

Am i missing something?

**Comment by Noot-tooN** [comment]
First of all thanks!

Tried out the sample code and it seems to be working with some errors, which are probably from my bad implementation. When i have have some workflows waiting on the lock when the lock gets freed, the workflows get duplicated for some reason. There is only 1 activity before the lock which always finishes successfully. Would appreciate help if you can assume what's going on, but i'll probably figure it out on my own after some trial and error.

Although there is currently a sample how to achieve something like this i still think it would be more convenient if we simply had something like `workflow.Lock(ctx, key)` or maybe `AtomicChildWorkflow(key)` but i guess that `workflow.Lock` is more universal.
Some benefits i see from this:
- It could probably avoid showing up in the temporal history in the UI
- Easier for devs to use, i probably wouldn't have this duplication of workflows happening :smile: 
- Temporal would guarantee that this works as intended

**Comment by cretz** [comment]
The benefit of Temporal workflows being a primitive is you can do anything you want here instead of Temporal providing some rigid primitive. What if you wanted a semaphore instead of a single item lock? Or what if you wanted some different logic on lock release? Or what if you wanted some other kind of critical section barrier across workflows that uses some other custom logic beyond naive lock/unlock? This is why we offer this as a sample so each can customize as they need, even if your current need is just for a simple lock/unlock.

It is possible in the future we may provide cross-workflow built-ins like this, but there are no near term plans to do so.
