### ISSUE TITLE
Wrap gRPC errors

### ISSUE THREAD

**Issue by cretz** [temporalio/features#59]
### Is your feature request related to a problem? Please describe.

Instead of just rethrowing gRPC errors, most (all?) SDKs wrap them. This is especially true for not-found.

### Describe the solution you'd like

Maybe use `WorkflowNotFound` and `ActivityNotFound` that wrap the gRPC versions? But what about the newer namespace not found that can be thrown instead of workflow not found but both have the not found code? Maybe it should just be `NotFound`? And if so, what does that really add over the raw gRPC errors?

Needs discussion.

**Comment by josh-berry** [comment]
The current error-handling regime seems like it's been pretty reasonable, and this would be a breaking change, no? Should we keep this or just close it?

**Comment by cretz** [comment]
Yeah, I would close this. If we want to revisit and discuss we can
