### ISSUE TITLE
SDKs should stop retrying on "Internal" server error

### ISSUE THREAD

**Issue by bergundy** [temporalio/features#6]
There was some work done for `Internal` and `Unavailable` errors differentiation on the server. Previously server returned only `Internal` and SDKs always retried it. Also SDKs always retry `Unavailable` but it wasn't returned by server until few month ago. Now, server returns both codes and uses `Internal` for non-retryable (something really bad happened on the server) and `Unavailable` for retryable.

To complete this work stream SDKs need to stop retry on `Internal`. In order to distinguish between the server versions that properly report `Internal` and `Unavailable` errors SDKs should use the [capabilities](https://github.com/temporalio/api/blob/b2b8ae6592a8730dd5be6d90569d1aea84e1712f/temporal/api/workflowservice/v1/request_response.proto#L751) reported in the `getSystemInfo` API call.

- [x] Go SDK (should automatically be supported in PHP SDK, verify with Anton)
- [x] Core SDK
- [x] TS SDK (client)
- [x] https://github.com/temporalio/sdk-java/issues/1315
- [x] PHP SDK https://github.com/temporalio/sdk-php/issues/221

**Comment by josh-berry** [comment]
@bergundy Can this be closed? Looks like it's done in all the SDKs.

**Comment by bergundy** [comment]
This can be closed.
Note that there's still work to be done to unify the retry behavior across SDKs: https://github.com/temporalio/features/issues/27
