### ISSUE TITLE
[Feature Request] Create compatible encryption libraries

### ISSUE THREAD

**Issue by lorensr** [temporalio/features#68]
### Is your feature request related to a problem? Please describe.

TS and Go encryption samples aren't compatible (despite my attempt to do things the same way): https://temporalio.slack.com/archives/C01DKSMU94L/p1657704501033689

Would be helpful to users if we gave them a cross-sdk tested library.

### Describe the solution you'd like

- Get the TS sample to be compatible, tested in this repo, and maybe change them all from samples to libraries.
- Maybe change them to use [NaCl](https://nacl.cr.yp.to/)? 

From @cretz:

> I'd recommend nacl-based encryption instead of AES-based encryption for cross-language compatibility for many reasons.

**Comment by cretz** [comment]
> Would be helpful to users if we gave them a cross-sdk tested library.

I think we need to be a bit careful giving any encryption "library" per se. But I would definitely support altering both the Go and TS samples to make them compatible with each other and use NaCl. How you'll test that is a different story.

I think the simplest approach for authenticated encryption is just secret box (no need for PKI setup). So https://pkg.go.dev/golang.org/x/crypto/nacl/secretbox in Go and I guess https://github.com/dchest/tweetnacl-js#secret-key-authenticated-encryption-secretbox or https://github.com/tonyg/js-nacl#secret-key-authenticated-encryption-crypto_secretbox or something in JS.

**Comment by lorensr** [comment]
@robholland agrees on not providing a library, and offered to help with compatibility

**Comment by robholland** [comment]
https://github.com/temporalio/samples-typescript/pull/171

**Comment by robholland** [comment]
To get to interop quickly I just adjusted the TS crypto usage rather than porting all of our samples to nacl.

**Comment by robholland** [comment]
@josh-berry this can actually be closed, the mentioned PR fixed the incompatibility. Not sure why it hadn't been closed already.
